@echo off
setlocal EnableExtensions
chcp 65001 >nul

set "SCRIPT_DIR=%~dp0"
if "%SCRIPT_DIR:~-1%"=="\" set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"

for %%A in ("%SCRIPT_DIR%") do set "HERE=%%~nxA"

set "ROOT=%SCRIPT_DIR%"
if /I "%HERE%"=="install" for %%A in ("%SCRIPT_DIR%\..") do set "ROOT=%%~fA"

call :MK "%ROOT%\input"
call :MK "%ROOT%\output"
call :MK "%ROOT%\logs"
call :MK "%ROOT%\report"
call :MK "%ROOT%\report\gui_smoke_screenshots"
call :MK "%ROOT%\workspace"
call :MK "%ROOT%\backup"
call :MK "%ROOT%\backup\default_apps"
call :MK "%ROOT%\backup\driver_guard"
call :MK "%ROOT%\backup\driver_guard\policy"
call :MK "%ROOT%\backup\driver_guard\driver_store"
call :MK "%ROOT%\backup\driver_guard\manifests"
call :MK "%ROOT%\backup\driver_guard\rank_repair"
call :MK "%ROOT%\backup\browser_bookmarks"
call :MK "%ROOT%\backup\browser_bookmarks\masters"
call :MK "%ROOT%\backup\hosts"
call :MK "%ROOT%\backup\nvidia_audio"
call :MK "%ROOT%\backup\virtualization"
call :MK "%ROOT%\profiles"
call :MK "%ROOT%\profiles\default_apps"
call :MK "%ROOT%\tools"
call :MK "%ROOT%\config"
call :MK "%ROOT%\config\icc"
call :MK "%ROOT%\data"
call :MK "%ROOT%\data\driver_guard"
call :MK "%ROOT%\data\nvidia_audio"
call :MK "%ROOT%\output\certificates"
call :MK "%ROOT%\output\driver_guard"
call :MK "%ROOT%\output\driver_guard\reg_fallback"
call :MK "%ROOT%\output\nvidia_audio"
call :MK "%ROOT%\output\ssh_keykit"
call :MK "%ROOT%\runtime"
call :MK "%ROOT%\wheelhouse"
call :MK "%ROOT%\release"
call :MK "%ROOT%\ripgrep"
call :MK "%ROOT%\._runtime"
call :MK "%ROOT%\docs"
call :MK "%ROOT%\docs\PDF"
call :MK "%ROOT%\tests"
call :MK "%ROOT%\system_core"
call :MK "%ROOT%\system_core\core"
call :MK "%ROOT%\system_core\services"
call :MK "%ROOT%\system_core\ui_nicegui"
call :MK "%ROOT%\system_core\powershell"
call :MK "%ROOT%\system_core\license"
call :MK "%ROOT%\system_core\license\files"
call :MK "%ROOT%\system_core\license\fallbacks"
call :MK "%ROOT%\system_core\wsl_assets"
call :MK "%ROOT%\system_core\wsl_assets\mc"
call :MK "%ROOT%\system_core\wsl_assets\micro"
call :MK "%ROOT%\system_core\wsl_assets\neovim"
call :MK "%ROOT%\system_core\windows_driver_guard"
call :MK "%ROOT%\system_core\nvidia_audio"
call :MK "%ROOT%\install"
call :MK "%ROOT%\install\download"
call :MK "%ROOT%\licenses"

exit /b 0

:MK
if not exist "%~1\" mkdir "%~1" >nul 2>nul
goto :eof
